**PANDAS**

In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("mtcars.csv")
df

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [3]:
df["mpg"].max()

33.9

In [4]:
df["mpg"][df['cyl']==6][df['wt']==2.620]

0    21.0
Name: mpg, dtype: float64

In [5]:
df.shape

(32, 12)

In [6]:
rows,column = df.shape

In [7]:
rows

32

In [8]:
column

12

In [9]:
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [10]:
df.tail()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

In [11]:
df.tail(3)

            model   mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
29   Ferrari Dino  19.7    6  145.0  175  3.62  2.77  15.5   0   1     5     6
30  Maserati Bora  15.0    8  301.0  335  3.54  3.57  14.6   0   1     5     8
31     Volvo 142E  21.4    4  121.0  109  4.11  2.78  18.6   1   1     4     2

In [12]:
df[2:5]

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [13]:
df.columns

Index(['model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

In [14]:
df.model

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: model, dtype: object

In [15]:
df[['model','wt']]

                  model     wt
0             Mazda RX4  2.620
1         Mazda RX4 Wag  2.875
2            Datsun 710  2.320
3        Hornet 4 Drive  3.215
4     Hornet Sportabout  3.440
5               Valiant  3.460
6            Duster 360  3.570
7             Merc 240D  3.190
8              Merc 230  3.150
9              Merc 280  3.440
10            Merc 280C  3.440
11           Merc 450SE  4.070
12           Merc 450SL  3.730
13          Merc 450SLC  3.780
14   Cadillac Fleetwood  5.250
15  Lincoln Continental  5.424
16    Chrysler Imperial  5.345
17             Fiat 128  2.200
18          Honda Civic  1.615
19       Toyota Corolla  1.835
20        Toyota Corona  2.465
21     Dodge Challenger  3.520
22          AMC Javelin  3.435
23           Camaro Z28  3.840
24     Pontiac Firebird  3.845
25            Fiat X1-9  1.935
26        Porsche 914-2  2.140
27         Lotus Europa  1.513
28       Ford Pantera L  3.170
29         Ferrari Dino  2.770
30        Maserati Bora  3.570
31           Volvo 142E  2.780

In [16]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [17]:
df.index

RangeIndex(start=0, stop=32, step=1)

In [18]:
#   df1=df.to_csv("x.csv")  --this is how we can store our fina dataset n csv format into computer

In [19]:
df =pd.read_csv('mtcars.csv',skiprows = 5)
df

      Hornet Sportabout  18.7  8    360  175  3.15   3.44  17.02  0  0.1  3  2
0               Valiant  18.1  6  225.0  105  2.76  3.460  20.22  1    0  3  1
1            Duster 360  14.3  8  360.0  245  3.21  3.570  15.84  0    0  3  4
2             Merc 240D  24.4  4  146.7   62  3.69  3.190  20.00  1    0  4  2
3              Merc 230  22.8  4  140.8   95  3.92  3.150  22.90  1    0  4  2
4              Merc 280  19.2  6  167.6  123  3.92  3.440  18.30  1    0  4  4
5             Merc 280C  17.8  6  167.6  123  3.92  3.440  18.90  1    0  4  4
6            Merc 450SE  16.4  8  275.8  180  3.07  4.070  17.40  0    0  3  3
7            Merc 450SL  17.3  8  275.8  180  3.07  3.730  17.60  0    0  3  3
8           Merc 450SLC  15.2  8  275.8  180  3.07  3.780  18.00  0    0  3  3
9    Cadillac Fleetwood  10.4  8  472.0  205  2.93  5.250  17.98  0    0  3  4
10  Lincoln Continental  10.4  8  460.0  215  3.00  5.424  17.82  0    0  3  4
11    Chrysler Imperial  14.7  8  440.0  230  3.23  5.345  17.42  0    0  3  4
12             Fiat 128  32.4  4   78.7   66  4.08  2.200  19.47  1    1  4  1
13          Honda Civic  30.4  4   75.7   52  4.93  1.615  18.52  1    1  4  2
14       Toyota Corolla  33.9  4   71.1   65  4.22  1.835  19.90  1    1  4  1
15        Toyota Corona  21.5  4  120.1   97  3.70  2.465  20.01  1    0  3  1
16     Dodge Challenger  15.5  8  318.0  150  2.76  3.520  16.87  0    0  3  2
17          AMC Javelin  15.2  8  304.0  150  3.15  3.435  17.30  0    0  3  2
18           Camaro Z28  13.3  8  350.0  245  3.73  3.840  15.41  0    0  3  4
19     Pontiac Firebird  19.2  8  400.0  175  3.08  3.845  17.05  0    0  3  2
20            Fiat X1-9  27.3  4   79.0   66  4.08  1.935  18.90  1    1  4  1
21        Porsche 914-2  26.0  4  120.3   91  4.43  2.140  16.70  0    1  5  2
22         Lotus Europa  30.4  4   95.1  113  3.77  1.513  16.90  1    1  5  2
23       Ford Pantera L  15.8  8  351.0  264  4.22  3.170  14.50  0    1  5  4
24         Ferrari Dino  19.7  6  145.0  175  3.62  2.770  15.50  0    1  5  6
25        Maserati Bora  15.0  8  301.0  335  3.54  3.570  14.60  0    1  5  8
26           Volvo 142E  21.4  4  121.0  109  4.11  2.780  18.60  1    1  4  2

In [20]:
import pandas as pd
import numpy as np
x = np.array([[1, 2], [3, 4], [2, 2], [9, 6]])

In [21]:
print(np.sum(x,axis=1))

[ 3  7  4 15]

In [22]:
import pandas as pd
import numpy as np

In [23]:
pd.read_csv('matches.csv')

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [24]:
data5=pd.read_csv('deliveries.csv')
data5

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [25]:
mask=data5['batsman_runs']==6
new=data5[mask]

four=new.groupby('batsman')

four['batsman_runs'].count().sort_values(ascending=False).head()

batsman
CH Gayle     266
SK Raina     174
RG Sharma    173
V Kohli      160
DA Warner    160
Name: batsman_runs, dtype: int64

In [26]:
mask1=data5['batsman']=='V Kohli'
new1=data5[mask1]
new2=new1.groupby('bowling_team')
new2['batsman_runs'].sum().sort_values(ascending=False).head()

bowling_team
Chennai Super Kings    706
Delhi Daredevils       661
Kings XI Punjab        483
Mumbai Indians         447
Sunrisers Hyderabad    439
Name: batsman_runs, dtype: int64

In [27]:
dataset=[12,15,14,100,17,19,2,30,31,27,25,26,19,99,85,110,14,15,16,25,16,17,18,34,35,39]
data=np.array(dataset)
m=np.mean(data)
print(m)
s=np.std(data)
s
for i in dataset:
    z_score=(i-m)/s
    if np.abs(z_score)>3:
        prnt(i)

33.07692307692308